// src/ui/repl/spinner.tsx
/**
 * spinner.tsx — small rotating braille spinner.
 *
 * Renders only while the REPL is in `streaming` or `compact`. Uses a local
 * setInterval with unref() so the timer can't keep the Node process alive
 * after the app exits.
 */

import React, { useEffect, useState } from "react";
import { Text } from "ink";

const FRAMES = ["⠋", "⠙", "⠸", "⠴", "⠦", "⠇"] as const;
const FRAME_MS = 80;

export interface SpinnerProps {
  readonly active: boolean;
  readonly label?: string;
  readonly color?: string;
}

export function Spinner(props: SpinnerProps): React.ReactElement | null {
  const [frame, setFrame] = useState(0);

  useEffect(() => {
    if (!props.active) return;
    const timer = setInterval(() => {
      setFrame((f) => (f + 1) % FRAMES.length);
    }, FRAME_MS);
    if (typeof timer.unref === "function") timer.unref();
    return () => clearInterval(timer);
  }, [props.active]);

  if (!props.active) return null;
  const ch = FRAMES[frame] ?? FRAMES[0];
  return (
    <Text color={props.color ?? "cyan"}>
      {ch}
      {props.label !== undefined ? ` ${props.label}` : ""}
    </Text>
  );
}

// src/ui/repl-solid/spinner.tsx
/**
 * spinner.tsx — animated braille spinner (OpenTUI/Solid port).
 *
 * Renders a single rotating braille character that cycles through 10 frames
 * while `active` is true. Uses Solid's createSignal + setInterval; the
 * interval is cleared via onCleanup so it never outlives the component.
 */

import { createSignal, onCleanup, Show, createEffect } from "solid-js";
import { theme } from "./theme.js";

const FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"] as const;

export interface SpinnerProps {
  readonly active?: boolean;
  readonly intervalMs?: number;
}

export function Spinner(props: SpinnerProps) {
  const active = () => props.active ?? true;
  const intervalMs = () => props.intervalMs ?? 80;

  const [frame, setFrame] = createSignal(0);

  createEffect(() => {
    if (!active()) return;
    const id = setInterval(() => {
      setFrame((f) => (f + 1) % FRAMES.length);
    }, intervalMs());
    onCleanup(() => clearInterval(id));
  });

  return (
    <Show when={active()}>
      <text fg={theme.streamingIndicator}>{FRAMES[frame()]}</text>
    </Show>
  );
}
