// src/ui/repl/status.tsx
/**
 * status.tsx — bottom status bar.
 *
 * Shows the current REPL state, permission mode, short session id, and a
 * cumulative token count. The token count is retrieved via a caller-supplied
 * getter — Phase 5 wires this up to the real ClaudeAgentSdkEngine usage
 * accumulator; Phase 2 passes a stub that returns 0.
 */

import React from "react";
import { Box, Text } from "ink";
import type { ReplState } from "./state.js";
import { Spinner } from "./spinner.js";

export type TokenGetter = () => number;

export interface StatusProps {
  readonly state: ReplState;
  readonly model: string;
  readonly getTokens: TokenGetter;
}

function shortSession(id: string | undefined): string {
  if (id === undefined || id.length === 0) return "—";
  return id.length > 8 ? id.slice(0, 8) : id;
}

function stateColor(name: ReplState["name"]): string {
  switch (name) {
    case "idle":
      return "green";
    case "streaming":
      return "cyan";
    case "awaiting-permission":
      return "yellow";
    case "compact":
      return "magenta";
    case "shutdown":
      return "gray";
  }
}

export function Status(props: StatusProps): React.ReactElement {
  const { state, model, getTokens } = props;
  const showSpinner = state.name === "streaming" || state.name === "compact";
  const pending = state.pendingPermission;
  return (
    <Box flexDirection="column" marginTop={1}>
      {pending !== undefined ? (
        <Box>
          <Text color="yellow">
            permission: {pending.toolName} — /approve or /deny
          </Text>
        </Box>
      ) : null}
      <Box>
        <Text color={stateColor(state.name)}>[{state.name}]</Text>
        <Text> </Text>
        <Text dimColor>
          {model} · {state.permissionMode} · session {shortSession(state.sessionId)} ·{" "}
          tokens {getTokens()}
        </Text>
        {showSpinner ? (
          <Box marginLeft={1}>
            <Spinner active={true} />
          </Box>
        ) : null}
      </Box>
    </Box>
  );
}

// src/ui/repl-solid/status.tsx
/**
 * status.tsx — bottom status bar (OpenTUI/Solid port).
 *
 * Shows the current REPL state name, model, permission mode, short session id,
 * token count, and — when a permission is pending — an inline alert.
 * Mirrors src/ui/repl/status.tsx responsibilities using OpenTUI primitives.
 */

import { createMemo, Show } from "solid-js";
import type { ReplState } from "../repl/state.js";
import { stateColor, theme } from "./theme.js";

export type TokenGetter = () => number;

export interface StatusProps {
  readonly state: ReplState;
  readonly model: string;
  readonly getTokens: TokenGetter;
}

function shortSession(id: string | undefined): string {
  if (id === undefined || id.length === 0) return "—";
  return id.length > 8 ? id.slice(0, 8) : id;
}

export function Status(props: StatusProps) {
  const color = createMemo(() => stateColor[props.state.name]);

  const infoLine = createMemo(
    () =>
      `[${props.state.name}] ${props.model} · ${props.state.permissionMode} · session ${shortSession(props.state.sessionId)} · tokens ${props.getTokens()}`,
  );

  const permissionLine = createMemo(() => {
    const p = props.state.pendingPermission;
    if (!p) return "";
    return `permission: ${p.toolName} — /approve or /deny`;
  });

  return (
    <box>
      <Show when={props.state.pendingPermission}>
        <text fg={theme.warning}>{permissionLine()}</text>
      </Show>
      <text fg={color()}>{infoLine()}</text>
    </box>
  );
}
