// src/ui/repl-solid/app.tsx
/**
 * app.tsx — Solid root for the OpenTUI REPL.
 *
 * Composes Transcript, Input, Status, Spinner, Dropdown. Drives the store
 * from engine events; handles SIGINT → shutdown; routes slash-prefixed
 * submits through the existing `dispatchSlashLine` pipeline and applies
 * the resulting `SlashCommandResult` back into the store.
 *
 * Phase 0c.5 change: slash-command dispatch + dropdown wiring landed.
 * Dropdown shows filtered candidates when input starts with "/". Enter
 * submits the current input as-is (no tab-autocomplete yet; that can
 * come later).
 */

import { Show, onMount, onCleanup, createEffect, createMemo } from "solid-js";
import { createReplStore } from "./store.js";
import { Transcript } from "./transcript.js";
import { Input } from "./input.js";
import { Status } from "./status.js";
import { Spinner } from "./spinner.js";
import { Dropdown } from "./dropdown.js";
import { dispatchSlashLine } from "../../cli/slash/dispatcher.js";
import type {
  SlashCommandResult,
  SlashCommandRegistry,
} from "../../cli/slash/index.js";
import type { NormalizedEvent } from "../../core/types.js";
import type { ReplEvent } from "../repl/state.js";
import type { AppProps } from "./types.js";

export type { AppProps };

let slashSeq = 0;

export function App(props: AppProps) {
  const { state, dispatch } = createReplStore({
    permissionMode: props.permissionMode,
  });

  // Engine event pump.
  onMount(() => {
    let cancelled = false;
    const pump = async (): Promise<void> => {
      try {
        for await (const evt of props.events) {
          if (cancelled) break;
          for (const action of translateEngineEvent(evt)) {
            dispatch(action);
          }
        }
      } catch {
        // Engine errors arrive via the `error` NormalizedEvent and are
        // translated above; iterator-level throws are rare.
      }
    };
    void pump();
    onCleanup(() => {
      cancelled = true;
    });
  });

  // SIGINT → shutdown.
  onMount(() => {
    const onSigInt = (): void => {
      dispatch({ type: "shutdown" });
    };
    process.once("SIGINT", onSigInt);
    onCleanup(() => {
      process.off("SIGINT", onSigInt);
    });
  });

  // Shutdown watcher.
  createEffect(() => {
    if (state.name === "shutdown") {
      props.onExit?.();
    }
  });

  const handleSubmit = (line: string): void => {
    if (line.length === 0) return;
    if (line.startsWith("/") && props.registry !== undefined) {
      const registry = props.registry;
      void (async () => {
        const result = await dispatchSlashLine(
          line,
          state,
          registry,
          props.slashDeps ?? {},
        );
        applySlashResult(result, dispatch, props.onSubmit, props.onSessionId);
      })();
      return;
    }
    dispatch({ type: "submit", text: line });
    props.onSubmit?.(line);
  };

  const getTokens = (): number => props.getTokens?.() ?? 0;

  // Dropdown candidates — non-empty and visible only when input starts with
  // "/" and a registry is available. Filter registry entries by the prefix
  // after "/".
  const dropdownCandidates = createMemo<
    ReadonlyArray<{ name: string; description: string }>
  >(() => {
    const registry = props.registry;
    if (registry === undefined) return [];
    const value = state.input.value;
    if (!value.startsWith("/")) return [];
    const prefix = value.slice(1).toLowerCase();
    return registry
      .list()
      .filter((c) => c.name.toLowerCase().startsWith(prefix));
  });

  return (
    <box flexDirection="column" flexGrow={1}>
      <Transcript entries={state.transcript} />
      <Show when={state.name === "streaming"}>
        <Spinner />
      </Show>
      <Show when={state.name !== "shutdown"}>
        <Input
          value={state.input.value}
          onChange={(value, cursor) =>
            dispatch({ type: "input-changed", value, cursor })
          }
          onSubmit={handleSubmit}
          onKey={(key) => dispatch({ type: "key", key })}
          disabled={state.name === "compact"}
        />
      </Show>
      <Show when={dropdownCandidates().length > 1}>
        <Dropdown candidates={dropdownCandidates()} selectedIndex={0} />
      </Show>
      <Status state={state} model={props.model} getTokens={getTokens} />
    </box>
  );
}

// ---------------------------------------------------------------------------
// Slash result → store dispatch
// ---------------------------------------------------------------------------

/**
 * Port of `applySlashResult` from src/ui/repl/app.tsx. Translates a
 * SlashCommandResult into store dispatches + optional onSubmit/onSessionId
 * callbacks. No Ink-specific API (no `ink.exit()` — shutdown propagates via
 * the reducer-event variant and App's onExit effect).
 */
function applySlashResult(
  result: SlashCommandResult,
  dispatch: (e: ReplEvent) => void,
  onSubmit?: (line: string) => void,
  onSessionId?: (sessionId: string) => void,
): void {
  slashSeq += 1;
  switch (result.kind) {
    case "message":
      dispatch({
        type: "system-entry",
        id: `slash-msg-${slashSeq}`,
        text: result.text,
      });
      return;
    case "error":
      dispatch({
        type: "system-entry",
        id: `slash-err-${slashSeq}`,
        text: `error: ${result.message}`,
      });
      return;
    case "reducer-event":
      dispatch(result.event);
      if (result.event.type === "session-id") {
        onSessionId?.(result.event.sessionId);
      }
      // /exit → reducer-event: { type: "shutdown" }. App's effect on
      // state.name === "shutdown" calls props.onExit, so no explicit call
      // needed here.
      return;
    case "engine-hint":
      dispatch({ type: "submit", text: result.prompt });
      onSubmit?.(result.prompt);
      return;
    case "ok":
      return;
  }
}

// ---------------------------------------------------------------------------
// Engine event → reducer actions
// ---------------------------------------------------------------------------

export function translateEngineEvent(evt: NormalizedEvent): ReplEvent[] {
  switch (evt.type) {
    case "text_delta":
      return [{ type: "stream-delta", text: evt.text }];
    case "tool_use_start":
      return [{ type: "tool-entry", id: evt.id, name: evt.name }];
    case "tool_use_input":
    case "tool_use_end":
      return [];
    case "tool_result":
      return [
        {
          type: "system-entry",
          id: `tr-${evt.toolUseId}`,
          text: evt.isError
            ? `tool error: ${evt.content.slice(0, 120)}`
            : `tool ok: ${evt.content.slice(0, 120).split("\n")[0] ?? ""}`,
        },
      ];
    case "message_stop":
      return [{ type: "stream-end" }];
    case "error":
      return [
        {
          type: "system-entry",
          id: `err-${Date.now()}`,
          text: `error: ${evt.error.message}`,
        },
        { type: "stream-end" },
      ];
    case "hook_event":
      return [
        {
          type: "system-entry",
          id: `hook-${evt.payload.hookId}-${evt.payload.subtype}`,
          text: `hook ${evt.payload.hookName} (${evt.payload.event}) ${evt.payload.subtype}`,
        },
      ];
    case "compaction": {
      const actions: ReplEvent[] = [];
      if (evt.payload.phase === "begin") {
        actions.push({
          type: "system-entry",
          id: `compaction-${Date.now()}`,
          text: `[compaction: ${evt.payload.trigger}]`,
        });
        actions.push({ type: "compact-begin" });
      } else {
        actions.push({ type: "compact-end" });
      }
      return actions;
    }
    case "cache_hit":
    case "cache_miss":
      return [];
  }
}

// Avoid unused-import errors when SlashCommandRegistry isn't referenced at
// runtime (it's only used as a type via AppProps).
export type { SlashCommandRegistry };

// src/ui/repl/app.tsx
/**
 * app.tsx — root <App> component for the interactive REPL.
 *
 * Responsibilities:
 *   - Own the reducer state (React useReducer).
 *   - Consume engine events (an AsyncIterable of NormalizedEvent) and dispatch
 *     matching reducer actions.
 *   - Render the transcript, input, status bar.
 *   - Handle Ctrl+C / SIGINT → shutdown → unmount.
 *
 * Phase 2 scope: wire text_delta / tool_use / message_stop / hook_event to
 * transcript + state transitions. Permission flow is stubbed: when a pending
 * permission request arrives, the status bar shows it and the user is
 * expected to type `/approve` or `/deny` (dispatcher comes in Phase 3).
 * Compaction hooks into `compact-begin`/`compact-end` reducer events — the
 * engine will emit a compaction variant in a later phase; until then the
 * reducer accepts the events for future wiring.
 */

import React, { useEffect, useReducer, useRef } from "react";
import { Box, useApp } from "ink";
import type { NormalizedEvent } from "../../core/types.js";
import type { PermissionMode } from "../../core/types.js";
import {
  createInitialState,
  reduce,
  createStubSlashRegistry,
  type ReplEvent,
} from "./state.js";
import { Transcript } from "./transcript.js";
import { Input } from "./input.js";
import { Status, type TokenGetter } from "./status.js";
import { dispatchSlashLine } from "../../cli/slash/dispatcher.js";
import type {
  BuildDefaultRegistryDeps,
  SlashCommandRegistry,
} from "../../cli/slash/index.js";

export interface AppProps {
  readonly events: AsyncIterable<NormalizedEvent>;
  readonly model: string;
  readonly permissionMode: PermissionMode;
  readonly registry?: SlashCommandRegistry;
  readonly getTokens?: TokenGetter;
  /** Deps threaded through the slash dispatcher into each SlashCommandContext. */
  readonly slashDeps?: BuildDefaultRegistryDeps;
  /** Called when the REPL should shut down (e.g. user typed /exit). */
  readonly onExit?: () => void;
  /** Called when the user submits a non-slash prompt — triggers the next engine turn. */
  readonly onSubmit?: (line: string) => void;
  /**
   * Called when /resume emits a session-id reducer event so the outer caller
   * can wire RunConfig.resumeFrom for the next turn.
   */
  readonly onSessionId?: (sessionId: string) => void;
}

export function App(props: AppProps): React.ReactElement {
  const registry = props.registry ?? createStubSlashRegistry();
  const getTokens = props.getTokens ?? (() => 0);
  const [state, dispatch] = useReducer(reduce, undefined, () =>
    createInitialState({ permissionMode: props.permissionMode }),
  );
  const ink = useApp();
  const eventsRef = useRef<AsyncIterable<NormalizedEvent>>(props.events);

  // Drive the reducer from engine events.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        for await (const evt of eventsRef.current) {
          if (cancelled) break;
          for (const action of translateEngineEvent(evt)) {
            dispatch(action);
          }
        }
      } catch {
        // Swallow — ClaudeAgentSdkEngine already surfaces errors via the
        // `error` NormalizedEvent. Iterator-level throws are extremely rare
        // and shouldn't crash the REPL.
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // Handle Ctrl+C / SIGINT → graceful shutdown.
  useEffect(() => {
    const onSigInt = () => {
      dispatch({ type: "shutdown" });
      setTimeout(() => ink.exit(), 50);
    };
    process.once("SIGINT", onSigInt);
    return () => {
      process.off("SIGINT", onSigInt);
    };
  }, [ink]);

  // Unmount once the state machine reaches shutdown.
  useEffect(() => {
    if (state.name === "shutdown") {
      props.onExit?.();
      setTimeout(() => ink.exit(), 20);
    }
  }, [state.name, ink]);

  const stateRef = useRef(state);
  stateRef.current = state;

  const onSubmit = (line: string): void => {
    if (line.length === 0) return;
    if (line.startsWith("/")) {
      // Phase 3: dispatch through the real registry.
      void (async () => {
        const result = await dispatchSlashLine(
          line,
          stateRef.current,
          registry,
          props.slashDeps ?? {},
        );
        applySlashResult(result, dispatch, ink, props.onSubmit, props.onSessionId);
      })();
      return;
    }
    // Normal prompt — append to transcript and transition to streaming.
    dispatch({ type: "submit", text: line });
    props.onSubmit?.(line);
  };

  return (
    <Box flexDirection="column">
      <Transcript entries={state.transcript} />
      {state.name !== "shutdown" ? (
        <Input
          state={state}
          registry={registry}
          onKey={(key) => dispatch({ type: "key", key })}
          onSubmit={onSubmit}
          disabled={state.name === "compact"}
        />
      ) : null}
      <Status state={state} model={props.model} getTokens={getTokens} />
    </Box>
  );
}

// ---------------------------------------------------------------------------
// Engine event → reducer actions
// ---------------------------------------------------------------------------

/**
 * Map a single NormalizedEvent to zero-or-more ReplEvents. Exported for
 * testability from state.test.ts (not currently exercised but kept public
 * for future integration tests in Phase 10).
 */
export function translateEngineEvent(evt: NormalizedEvent): ReplEvent[] {
  switch (evt.type) {
    case "text_delta":
      return [{ type: "stream-delta", text: evt.text }];
    case "tool_use_start":
      return [
        {
          type: "tool-entry",
          id: evt.id,
          name: evt.name,
        },
      ];
    case "tool_use_input":
    case "tool_use_end":
      return [];
    case "tool_result":
      // Surface a compact line so the user sees tool completion.
      return [
        {
          type: "system-entry",
          id: `tr-${evt.toolUseId}`,
          text: evt.isError
            ? `tool error: ${evt.content.slice(0, 120)}`
            : `tool ok: ${evt.content.slice(0, 120).split("\n")[0] ?? ""}`,
        },
      ];
    case "message_stop":
      return [{ type: "stream-end" }];
    case "error":
      return [
        {
          type: "system-entry",
          id: `err-${Date.now()}`,
          text: `error: ${evt.error.message}`,
        },
        { type: "stream-end" },
      ];
    case "hook_event":
      return [
        {
          type: "system-entry",
          id: `hook-${evt.payload.hookId}-${evt.payload.subtype}`,
          text: `hook ${evt.payload.hookName} (${evt.payload.event}) ${evt.payload.subtype}`,
        },
      ];
    case "compaction": {
      const actions: ReplEvent[] = [];
      if (evt.payload.phase === "begin") {
        // Add a transcript entry so the user sees that compaction occurred.
        actions.push({
          type: "system-entry",
          id: `compaction-${Date.now()}`,
          text: `[compaction: ${evt.payload.trigger}]`,
        });
        actions.push({ type: "compact-begin" });
      } else {
        actions.push({ type: "compact-end" });
      }
      return actions;
    }
    case "cache_hit":
    case "cache_miss":
      // Analytics-only events — no UI action needed.
      return [];
  }
}

// ---------------------------------------------------------------------------
// Slash result → reducer event / transcript / engine hint
// ---------------------------------------------------------------------------

let slashSeq = 0;

/**
 * Translate a `SlashCommandResult` into reducer dispatches + optional
 * `onSubmit` callback (for engine-hint prompts). Exported for tests.
 */
export function applySlashResult(
  result: import("../../cli/slash/index.js").SlashCommandResult,
  dispatch: (e: ReplEvent) => void,
  ink: ReturnType<typeof useApp>,
  onSubmit?: (line: string) => void,
  onSessionId?: (sessionId: string) => void,
): void {
  slashSeq += 1;
  switch (result.kind) {
    case "message":
      dispatch({
        type: "system-entry",
        id: `slash-msg-${slashSeq}`,
        text: result.text,
      });
      return;
    case "error":
      dispatch({
        type: "system-entry",
        id: `slash-err-${slashSeq}`,
        text: `error: ${result.message}`,
      });
      return;
    case "reducer-event":
      dispatch(result.event);
      // /exit result surfaces as a shutdown reducer event — unmount ink.
      if (result.event.type === "shutdown") {
        setTimeout(() => ink.exit(), 20);
      }
      // /resume emits session-id — notify outer caller so it can wire resumeFrom.
      if (result.event.type === "session-id") {
        onSessionId?.(result.event.sessionId);
      }
      return;
    case "engine-hint":
      // Inject the hint as if the user had typed it — triggers a turn.
      dispatch({ type: "submit", text: result.prompt });
      onSubmit?.(result.prompt);
      return;
    case "ok":
      return;
  }
}
