// src/ui/repl-solid/transcript.tsx
/**
 * transcript.tsx — OpenTUI/Solid port of src/ui/repl/transcript.tsx.
 *
 * Renders the transcript array from the REPL state. Each entry is rendered
 * as a <box> inside a <scrollbox> so overflow scrolls.
 *
 * Assistant entries use <code filetype="markdown" streaming={true}> from
 * @opentui/core for automatic markdown rendering and streaming support.
 * All other kinds render as plain <text>.
 */

import { For, Show } from "solid-js";
import type { TranscriptEntry } from "../repl/state.js";
import { entryColor } from "./theme.js";

export interface TranscriptProps {
  readonly entries: readonly TranscriptEntry[];
}

function UserEntry(props: { text: string }) {
  return (
    <box>
      <text fg={entryColor.user}>&gt; {props.text}</text>
    </box>
  );
}

function AssistantEntry(props: { text: string }) {
  return (
    <Show when={props.text.length > 0}>
      <box flexDirection="column">
        <code filetype="markdown" streaming={true} content={props.text} />
      </box>
    </Show>
  );
}

function ToolEntry(props: { name: string; summary?: string }) {
  const detail = () =>
    props.summary !== undefined && props.summary.length > 0
      ? ` — ${props.summary}`
      : "";
  return (
    <box>
      <text fg={entryColor.tool}>[{props.name}]{detail()}</text>
    </box>
  );
}

function SystemEntry(props: { text: string }) {
  return (
    <box>
      <text fg={entryColor.system}>{props.text}</text>
    </box>
  );
}

export function Transcript(props: TranscriptProps) {
  return (
    <scrollbox flexGrow={1}>
      <For each={props.entries as TranscriptEntry[]}>
        {(entry) => {
          switch (entry.kind) {
            case "user":
              return <UserEntry text={entry.text} />;
            case "assistant":
              return <AssistantEntry text={entry.text} />;
            case "tool":
              return (
                <ToolEntry
                  name={entry.tool?.name ?? "tool"}
                  summary={entry.tool?.summary ?? entry.text}
                />
              );
            case "system":
              return <SystemEntry text={entry.text} />;
          }
        }}
      </For>
    </scrollbox>
  );
}

// src/ui/repl/transcript.tsx
/**
 * transcript.tsx — renders past turns.
 *
 * Assistant text is rendered as streaming markdown via ink-markdown. User,
 * tool, and system entries are plain text. Full rendering of tool input /
 * output is out of scope for Phase 2 — tool rows show name + summary only.
 */

import React from "react";
import { Box, Text } from "ink";
// ink-markdown is built against React 16 types; cast to any to sidestep the
// JSX element-type mismatch with React 19 @types/react (same workaround we
// used before the ink-REPL rewrite).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
import MarkdownRaw from "ink-markdown";
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const Markdown: any = MarkdownRaw;
import type { TranscriptEntry } from "./state.js";

export interface TranscriptProps {
  readonly entries: readonly TranscriptEntry[];
}

function UserEntry(props: { text: string }): React.ReactElement {
  return (
    <Box>
      <Text color="cyan">&gt; {props.text}</Text>
    </Box>
  );
}

function AssistantEntry(props: { text: string }): React.ReactElement {
  if (props.text.length === 0) return <Box />;
  return (
    <Box flexDirection="column">
      <Markdown>{props.text}</Markdown>
    </Box>
  );
}

function ToolEntry(props: {
  name: string;
  summary?: string;
}): React.ReactElement {
  const detail = props.summary !== undefined && props.summary.length > 0 ? ` — ${props.summary}` : "";
  return (
    <Box>
      <Text color="yellow">[{props.name}]</Text>
      <Text dimColor>{detail}</Text>
    </Box>
  );
}

function SystemEntry(props: { text: string }): React.ReactElement {
  return (
    <Box>
      <Text dimColor italic>
        {props.text}
      </Text>
    </Box>
  );
}

export function Transcript(props: TranscriptProps): React.ReactElement {
  return (
    <Box flexDirection="column">
      {props.entries.map((entry) => {
        switch (entry.kind) {
          case "user":
            return <UserEntry key={entry.id} text={entry.text} />;
          case "assistant":
            return <AssistantEntry key={entry.id} text={entry.text} />;
          case "tool":
            return (
              <ToolEntry
                key={entry.id}
                name={entry.tool?.name ?? "tool"}
                summary={entry.tool?.summary ?? entry.text}
              />
            );
          case "system":
            return <SystemEntry key={entry.id} text={entry.text} />;
        }
      })}
    </Box>
  );
}
